### ISSUE TITLE
CollectBox

### ISSUE THREAD

**Issue by hammerheadlemon** [fniessen/emacs-leuven#1]
Thanks for making this available. The org-agenda stuff in here is awesome.

I'm struggling to understand the CollectBox feature though. Do I capture something (a Task, note or whatever), then C-c-C-c into org-files/refile.org, then use CollectBox to refile into other org files? When I try to do this, I see a "Sticky Buffer - use r to refresh" message, or a ~/refile.org not found error. I'm not doing something right! Can you help? Thank you.

**Comment by fniessen** [comment]
Sorry for my late intervention...

So, the principle is that you capture things on the fly, as soon as they enter your mind. Once captured with C-c c <X> (where X is t for task, n for note, etc.), they can leave your mind, as they're stored in your refile.org file.

Then, fire up (with f7 in my config) your "focus" view to see them all, and refile them (once a day) to their appropriate place.

In my case, the file refile.org is in ~/org/ directory. Maybe I should have a check for the right location.

Does the above help you?  Don't hesitate to come back!
