### ISSUE TITLE
Incompatibility causing an error with AUCTeX >= 13.0.0

### ISSUE THREAD

**Issue by tsdh** [fniessen/emacs-leuven#5]
A recent user report (see below) showed that the auctex customizations in leuven cause an error with auctex 13.0.0 and above.  The problem is that leuven accesses and modifies obsolete variables which we removed with version 13.0.0, concretely `TeX-view-style` and `TeX-output-view-style`.  Viewer configuration is now only supported via `TeX-view-program-selection`.

See https://lists.gnu.org/archive/html/auctex/2020-12/msg00019.html for details.

**Comment by fniessen** [comment]
Dear @tsdh , thanks for the head-ups.
